### PR TITLE
Week 2 Linux branch added

### PR DESCRIPTION
**Pull request by faree12**
Screenshot 2023-02-23 at 23 24 44
Screenshot 2023-02-23 at 23 28 47
Screenshot 2023-02-23 at 23 34 36
Screenshot 2023-02-23 at 23 35 21
Screenshot 2023-02-23 at 23 36 51
Screenshot 2023-02-24 at 00 03 20
Screenshot 2023-02-24 at 00 06 44
Screenshot 2023-02-23 at 23 51 45
Screenshot 2023-02-23 at 23 48 20
-images.githubusercontent.com/108369524/221052672-f8a6cdba-2ebf-4d22
Screenshot 2023-02-23 at 23 44 46
-a0d1-0f476726f82d.png">

### CODE REVIEW

**Review by borisbradic — CHANGES_REQUESTED** [review]
It seems like you are missing couple screenshots. Please check it.

**Comment by faree12** [comment]
There it is. I dont know how they didnt upload. I hope so they are all here now.

Screenshot 2023-02-23 at 23 36 51
d-d7273b6146f4.png">

**Comment by faree12** [comment]
Screenshot 2023-02-23 at 23 36 51

**Review by borisbradic — CHANGES_REQUESTED** [review]
I don't see "bandit8" here, please check, maybe you didn't upload it again.

**Comment by faree12** [comment]
Screenshot 2023-02-24 at 20 34 35
Im sorry. I hope so thats it now.

**Review by borisbradic — APPROVED** [review]
Seems all now.

**Pull request merged**
